package com.example.mnrader.model

enum class DogBreed(val id: Int, val breedName: String) {
    MALTESE(1, "말티즈"),
    POMERANIAN(2, "포메라니안"),
    FRENCH_BULLDOG(3, "프렌치 불도그"),
    CHIHUAHUA(4, "치와와"),
    BEAGLE(5, "비글"),
    YORKSHIRE_TERRIER(6, "요크셔 테리어"),
    DACHSHUND(7, "닥스훈트"),
    PUG(8, "퍼그"),
    SHIH_TZU(9, "시츄"),
    TERRIER(10, "테리어견"),
    SPITZ(11, "스피츠"),
    JAPANESE_SPITZ(12, "일본 스피츠"),
    GERMAN_SPITZ(13, "독일 스피츠"),
    POODLE(14, "푸들"),
    SHIBA_INU(15, "시바견"),
    AKITA_INU(16, "아키타견"),
    SCHIPPERKE(17, "스키퍼키"),
    ENGLISH_COCKER_SPANIEL(18, "잉글리시 코커 스패니얼"),
    LHASA_APSO(19, "라사압소"),
    BOXER(20, "복서"),
    DALMATIAN(21, "달마티안"),
    MINIATURE_PINSCHER(22, "미니어처 핀셔"),
    BRUSSELS_GRIFFON(23, "브뤼셀 그리펀"),
    JACK_RUSSELL_TERRIER(24, "잭 러셀 테리어"),
    AUSTRALIAN_SILKY_TERRIER(25, "오스트레일리안 실키 테리어"),
    PUNGSAN_DOG(26, "풍산개"),
    SAPSALI(27, "삽살개"),
    PRACTICAL_DOG(28, "실용견"),
    BOSTON_TERRIER(29, "보스턴 테리어"),
    TIBETAN_TERRIER(30, "티베탄 테리어"),
    TOY_POODLE(31, "토이 푸들"),
    MINIATURE_SCHNAUZER(32, "미니어처 슈나우저"),
    BICHON_FRISE(33, "비숑프리제"),
    BORDER_COLLIE(34, "보더콜리"),
    SAMOYED(35, "사모예드"),
    WELSH_CORGI(36, "웰시코기"),
    JINDO_DOG(37, "진돗개"),
    CHOW_CHOW(38, "차우차우"),
    SIBERIAN_HUSKY(39, "시베리안 허스키"),
    BULL_TERRIER(40, "불 테리어"),
    GREAT_PYRENEES(41, "그레이트 피레니즈"),
    PIT_BULL_TERRIER(42, "핏불 테리어"),
    MALINOIS(43, "말리노이즈"),
    LABRADOR_RETRIEVER(44, "래브라도 리트리버"),
    GERMAN_SHEPHERD(45, "저먼 셰퍼드"),
    GOLDEN_RETRIEVER(46, "골든 리트리버"),
    TIBETAN_MASTIFF(47, "티베탄 마스티프"),
    CHESAPEAKE_BAY_RETRIEVER(48, "체서피크 베이 리트리버"),
    FLAT_COATED_RETRIEVER(49, "플랫 코티드 리트리버"),
    CURLY_COATED_RETRIEVER(50, "컬리 코티드 리트리버"),
    TOSA_INU(51, "도사견"),
    BLOODHOUND(52, "블러드하운드"),
    BULLMASTIFF(53, "불마스티프"),
    MASTIFF(54, "마스티프"),
    MALINOIS_DUP(55, "말리노이즈"),
    BELGIAN_SHEEPDOG(56, "벨지안 십도그"),
    DOBERMAN_PINSCHER(57, "도베르만 핀셔"),
    GIANT_POODLE(58, "자이언트 푸들"),
    KANGAL(59, "캉갈"),
    GREYHOUND(60, "그레이 하운드"),
    GREAT_DANE(61, "그레이트 데인");

    companion object {
        fun fromId(id: Int): DogBreed? = DogBreed.entries.find { it.id == id }
    }
} 